---
- block:
  - name: Create CMS database
    mysql_db:
      name: "{{ cms_db_name }}"
      state: present

  - name: Create CRM database
    mysql_db:
      name: "{{ crm_db_name }}"
      state: present
    when: civicrm == 'Yes'

  - name: Create CRM logging database
    mysql_db:
      name: "{{ crm_logging_db_name }}"
      state: present
    when: civicrm == 'Yes' and crm_logging_db_name|default('blank', True) != 'blank'

  - name: Create MySQL User and set db permissions
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ lookup('community.general.passwordstore', client + '/' + hostname + '/' + bare_url + '/mysql create=true length=32 nosymbols=yes') }}"
      priv: "{{ cms_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,LOCK TABLES,CREATE TEMPORARY TABLES,CREATE VIEW{% if crm_db_name|default('blank', True) != 'blank' %}/{{ crm_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,LOCK TABLES,CREATE TEMPORARY TABLES,TRIGGER,CREATE ROUTINE,ALTER ROUTINE,CREATE VIEW,SHOW VIEW,REFERENCES{% endif %}{% if crm_logging_db_name|default('blank', True) != 'blank' %}/{{ crm_logging_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,LOCK TABLES,CREATE TEMPORARY TABLES,TRIGGER,CREATE ROUTINE,ALTER ROUTINE,CREATE VIEW,SHOW VIEW,REFERENCES{% endif %}"
      host: 'localhost'
      state: present
      append_privs: yes

  - name: Create a .my.cnf
    ansible.builtin.template:
      src: templates/my.cnf.j2
      dest: "$HOME/.my.cnf"
    become_user: "{{ run_as_user }}"
    tags: my.cnf

  when: cms != 'Static'
